name: nsd_platform_interface
description: Flutter network service discovery plugin (platform interface submodule - will be installed with the parent plugin).
version: 1.6.1
repository: https://github.com/sebastianhaberey/nsd/tree/main/nsd_platform_interface
issue_tracker: https://github.com/sebastianhaberey/nsd/issues
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.3
  uuid: ^3.0.7
  provider: ^6.0.4
  collection: 1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
